import { requireRole } from './auth.js';
import { getMenu, getMyTransactions, purchase } from './database.js';
import { rupiah, escapeHtml, jakartaNow, setMessage } from './utils.js';

const state = { menu: [], cart: [], profile: null };
const cartItem = id => state.cart.find(x => x.id === id);
function renderMenu() { document.getElementById('menu-list').innerHTML = state.menu.filter(m=>m.is_available).map(m => `<article class="menu-card ${m.stock_quantity === 0 ? 'sold-out' : ''}"><p class="category">${escapeHtml(m.category)}</p><h3>${escapeHtml(m.name)}</h3><strong>${rupiah(m.price)}</strong><small>${m.stock_quantity > 0 ? `Stok: ${m.stock_quantity}` : 'Stok habis'}</small><button data-add="${m.id}" ${m.stock_quantity === 0 ? 'disabled' : ''}>${m.stock_quantity === 0 ? 'Habis' : 'Tambah'}</button></article>`).join('') || '<p class="muted">Belum ada menu tersedia.</p>'; }
function renderCart() { const el=document.getElementById('cart-items'); const count=state.cart.reduce((n,x)=>n+x.quantity,0), total=state.cart.reduce((n,x)=>n+x.quantity*x.price,0); el.innerHTML=state.cart.length ? state.cart.map(x=>`<div class="cart-line"><div><strong>${escapeHtml(x.name)}</strong><small>${rupiah(x.price)}</small></div><div class="quantity"><button data-change="${x.id}" data-delta="-1" aria-label="Kurangi">−</button><span>${x.quantity}</span><button data-change="${x.id}" data-delta="1" aria-label="Tambah">+</button></div></div>`).join('') : '<p class="muted">Keranjang masih kosong.</p>'; document.getElementById('cart-count').textContent=`${count} item`; document.getElementById('cart-total').textContent=rupiah(total); document.getElementById('checkout-button').disabled=!count; }
async function renderToday() { const {date}=jakartaNow(); document.getElementById('today-date').textContent=date; const rows=await getMyTransactions(date); document.getElementById('today-purchases').innerHTML=rows.length ? rows.map(t=>`<div class="transaction-row"><div><strong>${t.transaction_items.map(i=>escapeHtml(i.item_name)).join(', ')}</strong><small>${t.transaction_time.slice(0,5)} · ${t.transaction_items.reduce((n,i)=>n+i.quantity,0)} item</small></div><strong>${rupiah(t.total_price)}</strong></div>`).join('') : '<p class="muted">Belum ada pembelian hari ini.</p>'; }
document.addEventListener('click', async e => { const add=e.target.dataset.add, change=e.target.dataset.change; if(add){const m=state.menu.find(x=>x.id===add), x=cartItem(add); if(x && x.quantity >= m.stock_quantity) return; if(x)x.quantity++; else state.cart.push({...m,quantity:1});renderCart();} if(change){const x=cartItem(change);if(Number(e.target.dataset.delta)>0 && x.quantity >= x.stock_quantity)return;x.quantity+=Number(e.target.dataset.delta);if(x.quantity<=0)state.cart=state.cart.filter(a=>a.id!==change);renderCart();} });
document.getElementById('checkout-button').addEventListener('click',async()=>{const b=document.getElementById('checkout-button'), msg=document.getElementById('purchase-message');b.disabled=true;try{const now=jakartaNow(); await purchase(state.cart,now.date,now.time);state.cart=[];await load();setMessage(msg,'Pembayaran berhasil. Terima kasih!');}catch(err){setMessage(msg,err.message.includes('Insufficient')?'Saldo tidak mencukupi.':'Pembayaran gagal. Silakan periksa kembali.',true);renderCart();}finally{b.disabled=!state.cart.length;}});
async function load(){state.profile=await requireRole('student');if(!state.profile)return;document.getElementById('student-name').textContent=state.profile.full_name||'Siswa';document.getElementById('balance').textContent=rupiah(state.profile.balance);state.menu=await getMenu();renderMenu();renderCart();await renderToday();}
load().catch(console.error);
