import { requireRole } from './auth.js';
import { getMenu, getReports, getStudents, saveMenu, deleteMenu, updateStudentBalance, createStudent, removeStudent } from './database.js';
import { rupiah, escapeHtml, displayDate, setMessage } from './utils.js';
let menu=[]; let students=[];
function renderMenu(){document.getElementById('admin-menu-list').innerHTML=`<table><thead><tr><th>Menu</th><th>Harga</th><th>Stok</th><th>Status</th><th></th></tr></thead><tbody>${menu.map(m=>`<tr><td><strong>${escapeHtml(m.name)}</strong><small>${escapeHtml(m.category)}</small></td><td>${rupiah(m.price)}</td><td>${m.stock_quantity}</td><td>${m.is_available?'Tersedia':'Disembunyikan'}</td><td><button class="secondary" data-edit-menu="${m.id}">Edit</button> <button class="danger" data-delete-menu="${m.id}">Hapus</button></td></tr>`).join('')}</tbody></table>`;}
function renderStudents(){const term=document.getElementById('student-search').value.toLowerCase();const visible=students.filter(s=>`${s.full_name} ${s.student_number||''}`.toLowerCase().includes(term));document.getElementById('student-list').innerHTML=`<table><thead><tr><th>Siswa</th><th>Saldo</th><th></th></tr></thead><tbody>${visible.map(s=>`<tr><td><strong>${escapeHtml(s.full_name)}</strong><small>${escapeHtml(s.student_number||'-')} | ${escapeHtml(s.class_name||'-')}</small></td><td>${rupiah(s.balance)}</td><td><button class="secondary" data-balance="${s.id}">Top up / saldo</button> <button class="danger" data-remove-student="${s.id}">Hapus</button></td></tr>`).join('')}</tbody></table>`;}
function renderReports(r){document.getElementById('report-cards').innerHTML=r.slice(0,3).map(x=>`<article class="stat-card"><small>${displayDate(x.transaction_date)}</small><strong>${rupiah(x.total_income)}</strong><span>${x.total_transactions} transaksi | ${x.total_items_sold} item</span></article>`).join('')||'<p class="muted">Belum ada transaksi.</p>';document.getElementById('daily-reports').innerHTML=`<table><thead><tr><th>Tanggal</th><th>Pendapatan</th><th>Item</th><th>Transaksi</th></tr></thead><tbody>${r.map(x=>`<tr><td>${displayDate(x.transaction_date)}</td><td>${rupiah(x.total_income)}</td><td>${x.total_items_sold}</td><td>${x.total_transactions}</td></tr>`).join('')}</tbody></table>`;}
function openMenu(m={}){const d=document.getElementById('menu-dialog');document.getElementById('menu-dialog-title').textContent=m.id?'Edit menu':'Tambah menu';document.getElementById('menu-id').value=m.id||'';document.getElementById('menu-name').value=m.name||'';document.getElementById('menu-category').value=m.category||'Lainnya';document.getElementById('menu-price').value=m.price||'';document.getElementById('menu-stock').value=m.stock_quantity??0;document.getElementById('menu-available').checked=m.is_available??true;d.showModal();}
document.getElementById('new-menu').onclick=()=>openMenu();document.getElementById('new-student').onclick=()=>document.getElementById('student-dialog').showModal();document.getElementById('student-search').oninput=renderStudents;document.querySelector('[data-close-dialog]').onclick=()=>document.getElementById('menu-dialog').close();document.querySelector('[data-close-student]').onclick=()=>document.getElementById('student-dialog').close();
document.getElementById('menu-form').onsubmit=async e=>{e.preventDefault();try{await saveMenu({id:document.getElementById('menu-id').value||undefined,name:document.getElementById('menu-name').value.trim(),category:document.getElementById('menu-category').value.trim(),price:Number(document.getElementById('menu-price').value),stock_quantity:Number(document.getElementById('menu-stock').value),is_available:document.getElementById('menu-available').checked});document.getElementById('menu-dialog').close();await load();}catch{setMessage(document.getElementById('menu-error'),'Menu gagal disimpan.',true);}};
document.getElementById('student-form').onsubmit=async e=>{e.preventDefault();const error=document.getElementById('student-error');try{await createStudent({full_name:document.getElementById('student-name-input').value.trim(),email:document.getElementById('student-email').value.trim(),password:document.getElementById('student-password').value,student_number:document.getElementById('student-number').value.trim(),class_name:document.getElementById('student-class').value.trim(),balance:Number(document.getElementById('student-balance').value)});e.target.reset();document.getElementById('student-dialog').close();await load();}catch(err){setMessage(error,err.message,true);}};
document.addEventListener('click',async e=>{const id=e.target.dataset.editMenu||e.target.dataset.deleteMenu||e.target.dataset.balance||e.target.dataset.removeStudent;if(!id)return;if(e.target.dataset.editMenu)openMenu(menu.find(x=>x.id===id));if(e.target.dataset.deleteMenu&&confirm('Hapus menu ini?')){await deleteMenu(id);await load();}if(e.target.dataset.balance){const s=students.find(x=>x.id===id),value=prompt(`Saldo baru untuk ${s.full_name} (Rp):`,s.balance);if(value!==null&&Number.isInteger(Number(value))&&Number(value)>=0){await updateStudentBalance(id,Number(value));await load();}}if(e.target.dataset.removeStudent&&confirm('Hapus akun siswa ini? Tindakan ini tidak dapat dibatalkan.')){await removeStudent(id);await load();}});
async function load(){if(!await requireRole('admin'))return;[menu,students]=await Promise.all([getMenu(),getStudents()]);const reports=await getReports();renderMenu();renderStudents();renderReports(reports);}load().catch(console.error);
